from quantax import Unit
from quantax.core.typing import SI
from quantax.unitful.unitful import Unitful

# Time units
s = Unitful(val=1.0, scale=0, unit=Unit({SI.s: 1}))
ms = Unitful(val=1.0, scale=-3, unit=Unit({SI.s: 1}))
us = Unitful(val=1.0, scale=-6, unit=Unit({SI.s: 1}))
ns = Unitful(val=1.0, scale=-9, unit=Unit({SI.s: 1}))
ps = Unitful(val=1.0, scale=-12, unit=Unit({SI.s: 1}))
fs = Unitful(val=1.0, scale=-15, unit=Unit({SI.s: 1}))

# Frequency units
Hz = Unitful(val=1.0, scale=0, unit=Unit({SI.s: -1}))
kHz = Unitful(val=1.0, scale=3, unit=Unit({SI.s: -1}))
MHz = Unitful(val=1.0, scale=6, unit=Unit({SI.s: -1}))
GHz = Unitful(val=1.0, scale=9, unit=Unit({SI.s: -1}))
THz = Unitful(val=1.0, scale=12, unit=Unit({SI.s: -1}))
PHz = Unitful(val=1.0, scale=15, unit=Unit({SI.s: -1}))

# Length units (meter)
m = Unitful(val=1.0, scale=0, unit=Unit({SI.m: 1}))
mm = Unitful(val=1.0, scale=-3, unit=Unit({SI.m: 1}))
um = Unitful(val=1.0, scale=-6, unit=Unit({SI.m: 1}))
nm = Unitful(val=1.0, scale=-9, unit=Unit({SI.m: 1}))
pm = Unitful(val=1.0, scale=-12, unit=Unit({SI.m: 1}))
fm = Unitful(val=1.0, scale=-15, unit=Unit({SI.m: 1}))
km = Unitful(val=1.0, scale=3, unit=Unit({SI.m: 1}))

# Power units (watt: kg⋅m²⋅s⁻³)
W = Unitful(val=1.0, scale=0, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -3}))
mW = Unitful(val=1.0, scale=-3, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -3}))
uW = Unitful(val=1.0, scale=-6, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -3}))
nW = Unitful(val=1.0, scale=-9, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -3}))
pW = Unitful(val=1.0, scale=-12, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -3}))
kW = Unitful(val=1.0, scale=3, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -3}))
MW = Unitful(val=1.0, scale=6, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -3}))
GW = Unitful(val=1.0, scale=9, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -3}))

# Voltage units (volt: kg⋅m²⋅s⁻³⋅A⁻¹)
V = Unitful(val=1.0, scale=0, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -3, SI.A: -1}))
mV = Unitful(val=1.0, scale=-3, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -3, SI.A: -1}))
uV = Unitful(val=1.0, scale=-6, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -3, SI.A: -1}))
nV = Unitful(val=1.0, scale=-9, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -3, SI.A: -1}))
kV = Unitful(val=1.0, scale=3, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -3, SI.A: -1}))
MV = Unitful(val=1.0, scale=6, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -3, SI.A: -1}))

# Current units (ampere)
A = Unitful(val=1.0, scale=0, unit=Unit({SI.A: 1}))
mA = Unitful(val=1.0, scale=-3, unit=Unit({SI.A: 1}))
uA = Unitful(val=1.0, scale=-6, unit=Unit({SI.A: 1}))
nA = Unitful(val=1.0, scale=-9, unit=Unit({SI.A: 1}))
pA = Unitful(val=1.0, scale=-12, unit=Unit({SI.A: 1}))
kA = Unitful(val=1.0, scale=3, unit=Unit({SI.A: 1}))

# Force units (newton: kg⋅m⋅s⁻²)
N = Unitful(val=1.0, scale=0, unit=Unit({SI.kg: 1, SI.m: 1, SI.s: -2}))
mN = Unitful(val=1.0, scale=-3, unit=Unit({SI.kg: 1, SI.m: 1, SI.s: -2}))
uN = Unitful(val=1.0, scale=-6, unit=Unit({SI.kg: 1, SI.m: 1, SI.s: -2}))
nN = Unitful(val=1.0, scale=-9, unit=Unit({SI.kg: 1, SI.m: 1, SI.s: -2}))
pN = Unitful(val=1.0, scale=-12, unit=Unit({SI.kg: 1, SI.m: 1, SI.s: -2}))
kN = Unitful(val=1.0, scale=3, unit=Unit({SI.kg: 1, SI.m: 1, SI.s: -2}))
MN = Unitful(val=1.0, scale=6, unit=Unit({SI.kg: 1, SI.m: 1, SI.s: -2}))

# Mass units (gram - note: SI base is kilogram)
kg = Unitful(val=1.0, scale=0, unit=Unit({SI.kg: 1}))
g = Unitful(val=1.0, scale=-3, unit=Unit({SI.kg: 1}))
mg = Unitful(val=1.0, scale=-6, unit=Unit({SI.kg: 1}))
ug = Unitful(val=1.0, scale=-9, unit=Unit({SI.kg: 1}))
ng = Unitful(val=1.0, scale=-12, unit=Unit({SI.kg: 1}))
pg = Unitful(val=1.0, scale=-15, unit=Unit({SI.kg: 1}))
ton = Unitful(val=1.0, scale=3, unit=Unit({SI.kg: 1}))  # metric ton

# Temperature units (kelvin)
K = Unitful(val=1.0, scale=0, unit=Unit({SI.K: 1}))
mK = Unitful(val=1.0, scale=-3, unit=Unit({SI.K: 1}))
uK = Unitful(val=1.0, scale=-6, unit=Unit({SI.K: 1}))
nK = Unitful(val=1.0, scale=-9, unit=Unit({SI.K: 1}))

# Energy units (joule: kg⋅m²⋅s⁻²)
J = Unitful(val=1.0, scale=0, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -2}))
mJ = Unitful(val=1.0, scale=-3, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -2}))
uJ = Unitful(val=1.0, scale=-6, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -2}))
nJ = Unitful(val=1.0, scale=-9, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -2}))
pJ = Unitful(val=1.0, scale=-12, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -2}))
kJ = Unitful(val=1.0, scale=3, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -2}))
MJ = Unitful(val=1.0, scale=6, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -2}))
GJ = Unitful(val=1.0, scale=9, unit=Unit({SI.kg: 1, SI.m: 2, SI.s: -2}))
